### PR TITLE
Add options for handling images with layer masks

### PR DESCRIPTION
**Pull request by msabramo**
In case the user has PSDs that happen to have layer masks (possibly
empty ones?) and wants to see what it looks like.

### CODE REVIEW

**Comment by Agamnentzar** [comment]
The throws are there mostly for testing and debugging, so I'll merge this but change the logic to be reversed, so it skips missing stuff by default, and throws only when you specify it in options.

**Comment by msabramo** [comment]
Oh cool! I had it throw by default, because I didn't want to change the existing behavior, in case folks were relying on it. But if you are okay with having it be permissive by default, that actually makes it more convenient for me. Thanks!

**Comment by Agamnentzar** [comment]
I published updated library

**Comment by msabramo** [comment]
Cool, I tested out ag-psd 6.0.0 and it's working great. Thanks for the super quick turnaround!

**Pull request merged**
